@fields = [{ field_name: 'sdt2', display_name: 'SĐT2', type: 'input', condition: %w[only_number = true] },
           { field_name: 'so_passport', display_name: 'Số Passport', type: 'input' },
           { field_name: 'ngay_cap_cmnd', display_name: 'Ngày cấp', type: 'date', condition: %w[date > 01/01/1976] },
           { field_name: 'ngay_cap_passport', display_name: 'Ngày cấp', type: 'date', condition: %w[date > 01/01/1976] },
           { field_name: 'noi_cap_cmnd', display_name: 'Nơi cấp', type: 'input' },
           { field_name: 'noi_cap_passport', display_name: 'Nơi cấp', type: 'input' },
           # Thong tin noi o
           { field_name: 'dia_chi_ho_khau', display_name: 'Hộ khẩu (số nhà, đường)', type: 'input' },
           { field_name: 'tinh_tp_ho_khau', display_name: 'TP/ Tỉnh', type: 'select' },
           { field_name: 'quan_huyen_ho_khau', display_name: 'Quận/ Huyện', type: 'select' },
           { field_name: 'phuong_xa_ho_khau', display_name: 'Phường/ Xã', type: 'select' },
           { field_name: 'dia_chi_hien_tai', display_name: 'Nơi ở hiện tại', type: 'input' },
           { field_name: 'tinh_tp_hien_tai', display_name: 'TP/ Tỉnh', type: 'select' },
           { field_name: 'quan_huyen_hien_tai', display_name: 'Quận/ Huyện', type: 'select' },
           { field_name: 'phuong_xa_hien_tai', display_name: 'Phường/ Xã', type: 'select' },
           { field_name: 'tinh_trang_nha_o', display_name: 'Tình trạng nhà ở', type: 'select' },
           { field_name: 'ten_chu_nha', display_name: 'Tên chủ nhà', type: 'input' },
           { field_name: 'sdt_chu_nha', display_name: 'Điện thoại chủ nhà', type: 'input' },
           { field_name: 'so_nam_o_tp_hien_tai', display_name: 'Số năm ở TP/ tỉnh hiện tại', type: 'input' },
           { field_name: 'so_nam_o_nha_hien_tai', display_name: 'Số năm ở nhà hiện tại', type: 'input' },
           { field_name: 'o_voi_ai', display_name: 'Ở với ai?', type: 'input' },
           # Thong tin khac
           { field_name: 'trinh_do_hoc_van', display_name: 'Trình độ học vấn', type: 'select' },
           { field_name: 'tinh_trang_hon_nhan', display_name: 'Tình trạng hôn nhân', type: 'select' },
           { field_name: 'so_nguoi_phu_thuoc', display_name: 'Số người phụ thuộc', type: 'select' },
           { field_name: 'so_con', display_name: 'Số con', type: 'select' },
           { field_name: 'tuoi_con_lon_nhat', display_name: 'Tuổi con lớn nhất', type: 'input' },
           { field_name: 'tuoi_con_nho_nhat', display_name: 'Tuổi con nhỏ nhất', type: 'input' },
           { field_name: 'email', display_name: 'Email', type: 'input' },
           { field_name: 'facebook', display_name: 'Facebook', type: 'input' },
           { field_name: 'zalo', display_name: 'Zalo', type: 'input' }
]