@fields = [{ field_name: 'phone2', display_name: 'SĐT2', type: 'input', condition: %w[only_number = true] },
           { field_name: 'passport_number', display_name: 'Số Passport', type: 'input' },
           { field_name: 'nic_date_of_issue', display_name: 'Ngày cấp', type: 'date', condition: %w[date > 01/01/1976] },
           { field_name: 'passport_date_of_issue', display_name: 'Ngày cấp', type: 'date', condition: %w[date > 01/01/1976] },
           { field_name: 'nic_place_of_issue', display_name: 'Nơi cấp', type: 'input' },
           { field_name: 'passport_place_of_issue', display_name: 'Nơi cấp', type: 'input' },
           { field_name: 'household_address', display_name: 'Hộ khẩu (số nhà, đường)', type: 'input' },
           { field_name: 'household_province', display_name: 'TP/ Tỉnh', type: 'select' },
           { field_name: 'household_district', display_name: 'Quận/ Huyện', type: 'select' },
           { field_name: 'household_ward', display_name: 'Phường/ Xã', type: 'select' },
           { field_name: 'current_address', display_name: 'Nơi ở hiện tại', type: 'input' },
           { field_name: 'current_province', display_name: 'TP/ Tỉnh', type: 'select' },
           { field_name: 'current_district', display_name: 'Quận/ Huyện', type: 'select' },
           { field_name: 'current_ward', display_name: 'Phường/ Xã', type: 'select' },
           { field_name: 'housing_status', display_name: 'Tình trạng nhà ở', type: 'select' },
           { field_name: 'house_owner_name', display_name: 'Tên chủ nhà', type: 'input' },
           { field_name: 'house_owner_phone', display_name: 'Điện thoại chủ nhà', type: 'input' },
           { field_name: 'number_years_current_city', display_name: 'Số năm ở TP/ tỉnh hiện tại', type: 'input' },
           { field_name: 'number_years_current_home', display_name: 'Số năm ở nhà hiện tại', type: 'input' },
           { field_name: 'stay_with', display_name: 'Ở với ai?', type: 'input' }
]